/*
 * suiji.java
 *
 * Created on __DATE__, __TIME__
 */

package twentyfour;

import java.util.Random;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author  __USER__
 */
public class suiji extends javax.swing.JFrame {

	/** Creates new form suiji */
	public suiji() {
		initComponents();
	}

	public void suiji(int random, JLabel jLabel) {
		if (random >= 1 && random <= 13) {
			String ulr = random + ".gif";
			ImageIcon bk = new ImageIcon(this.getClass().getResource(ulr));
			jLabel.setIcon(bk);
		}
		if (random >= 14 && random <= 26) {
			// random=random-13;
			String ulr = random + ".gif";
			ImageIcon bk = new ImageIcon(this.getClass().getResource(ulr));
			jLabel.setIcon(bk);
		}
		if (random >= 27 && random <= 39) {
			//random=random-26;
			String ulr = random + ".gif";
			ImageIcon bk = new ImageIcon(this.getClass().getResource(ulr));
			jLabel.setIcon(bk);
		}
		if (random >= 40 && random <= 52) {
			//random=random-39;
			String ulr = random + ".gif";
			ImageIcon bk = new ImageIcon(this.getClass().getResource(ulr));
			jLabel.setIcon(bk);
		}

	}
	public  int[] random(){
		 int a[]=new int[4];
			int n = 52;
			int b=0;
			Random rand = new Random();
			boolean[] bool = new boolean[4];
			int num = 0;
			for (int i = 0; i <n; i++) {
			do {
			// 如果产生的数相同继续循环
			num = rand.nextInt(n)+1;
			} while (bool[num]);
			bool[num] = true;
			a[b]=num;
			b++;
			}
			
		return a;
		 
	 }

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel2.setText("\u56fe\u7247\u663e\u793a\u5904\uff1a");

		jButton1.setText("\u6d17\u724c");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(260, 260, 260)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				332,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				90,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				142,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				26,
																				26,
																				26))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addContainerGap(
																				500,
																				Short.MAX_VALUE)))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				103,
																				103,
																				103)
																		.addComponent(
																				jLabel2)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				258,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				183,
																				183,
																				183)
																		.addComponent(
																				jButton1)))
										.addContainerGap(135, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		
		int[] a=random();
		suiji(a[1], jLabel1);
		System.out.println(a[1]);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new suiji().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}