/*
 * dj24dian.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import model.DataConnect;
import model.tread;

/**
 * 
 * @author __USER__
 */
public class dj24dian extends javax.swing.JFrame {
	static int[] t = new int[4];
	static int p = 1;
	static int m = 0;

	/** Creates new form dj24dian */
	public dj24dian() {

		initComponents();
		this.setLocationRelativeTo(null);
		final int time = 60;
		final tread t = new tread(time, jLabel6, jLabel3);
		t.start();
	}

	public int suiji(int random, JButton jButton) {
		if (random >= 1 && random <= 13) {
			String ulr = random + ".gif";
			ImageIcon bk = new ImageIcon(this.getClass().getResource(ulr));
			jButton.setIcon(bk);

		}
		if (random >= 14 && random <= 26) {
			// random=random-13;
			String ulr = random + ".gif";
			ImageIcon bk = new ImageIcon(this.getClass().getResource(ulr));
			jButton.setIcon(bk);
			random = random - 13;
		}
		if (random >= 27 && random <= 39) {
			// random=random-26;
			String ulr = random + ".gif";
			ImageIcon bk = new ImageIcon(this.getClass().getResource(ulr));
			jButton.setIcon(bk);
			random = random - 26;
		}
		if (random >= 40 && random <= 52) {
			// random=random-39;
			String ulr = random + ".gif";
			ImageIcon bk = new ImageIcon(this.getClass().getResource(ulr));
			jButton.setIcon(bk);
			random = random - 39;
		}
		return random;

	}

	public int[] random() {
		int a[] = new int[4];
		int n = 52;
		int b = 0;
		Random rand = new Random();
		boolean[] bool = new boolean[4];
		int num = 0;
		for (int i = 0; i < n; i++) {
			do {
				// 如果产生的数相同继续循环
				num = rand.nextInt(n) + 1;
			} while (bool[num]);
			bool[num] = true;
			a[b] = num;
			b++;
		}

		return a;

	}

	public Boolean Contrast(String answer) throws SQLException,
			ClassNotFoundException {
		Boolean decide = false;// 判断答案的依据
		String sql = "select * from 24answer where result='" + answer + "'";
		ResultSet rs = DataConnect.getStat().executeQuery(sql);
		if (rs.next()) {
			decide = true;
		}
		return decide;
	}

	public void upScore(int i, int j) {
		try {
			String sql = "insert into  twentyfour (uid,utime,uscore) values ('"
					+ 123 + "','" + i + "','" + j + "')";
			DataConnect.getStat().executeUpdate(sql);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel3 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jPanel6 = new javax.swing.JPanel();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jButton10 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();
		jButton13 = new javax.swing.JButton();
		jButton14 = new javax.swing.JButton();
		jButton15 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jLabel13 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel3.setBackground(new java.awt.Color(53, 52, 54));

		jPanel4.setBackground(new java.awt.Color(100, 38, 15));

		jPanel5.setBackground(new java.awt.Color(58, 154, 80));

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 411,
				Short.MAX_VALUE));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 133,
				Short.MAX_VALUE));

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel1.setForeground(new java.awt.Color(255, 195, 134));
		jLabel1.setText("\u5feb\u4e50\u6251\u514b24\u70b9");

		jTextField1.setBackground(new java.awt.Color(240, 240, 240));
		jTextField1.setBorder(null);

		jPanel6.setBackground(new java.awt.Color(255, 255, 255));

		jButton2.setBackground(new java.awt.Color(245, 245, 231));
		jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jButton2.setText("+");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setBackground(new java.awt.Color(245, 245, 231));
		jButton3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jButton3.setText("-");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setBackground(new java.awt.Color(245, 245, 231));
		jButton4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jButton4.setText("\u00d7");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5.setBackground(new java.awt.Color(245, 245, 231));
		jButton5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jButton5.setText("\u00f7");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setBackground(new java.awt.Color(245, 245, 231));
		jButton6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jButton6.setText("\uff08");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jButton7.setBackground(new java.awt.Color(245, 245, 231));
		jButton7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jButton7.setText("\uff09");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		jButton8.setBackground(new java.awt.Color(245, 245, 231));
		jButton8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jButton8.setText("\u2190");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		jButton9.setBackground(new java.awt.Color(245, 245, 231));
		jButton9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jButton9.setText("\u6e05\u9664");
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});

		jButton10.setBackground(new java.awt.Color(245, 245, 231));
		jButton10.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jButton10.setText("\u6d17\u724c");
		jButton10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton10ActionPerformed(evt);
			}
		});

		jButton11.setBackground(new java.awt.Color(245, 245, 231));
		jButton11.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jButton11.setText("\u786e\u5b9a");
		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton11ActionPerformed(evt);
			}
		});

		jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/picture/图片背景.jpg"))); // NOI18N
		jButton12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton12ActionPerformed(evt);
			}
		});

		jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/picture/图片背景.jpg"))); // NOI18N
		jButton13.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton13ActionPerformed(evt);
			}
		});

		jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/picture/图片背景.jpg"))); // NOI18N
		jButton14.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton14ActionPerformed(evt);
			}
		});

		jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/picture/图片背景.jpg"))); // NOI18N
		jButton15.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton15ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout
				.setHorizontalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jButton7,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jButton6,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jButton5,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jButton4,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jButton3,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jButton2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																55,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												40, Short.MAX_VALUE)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jButton14,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																91,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton12,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																88,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jButton15, 0,
																0,
																Short.MAX_VALUE)
														.addComponent(
																jButton13,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																94,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(31, 31, 31)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(
																jButton11,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jButton10,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jButton8,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jButton9,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel6Layout
				.setVerticalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel6Layout
																		.createSequentialGroup()
																		.addGap(
																				16,
																				16,
																				16)
																		.addComponent(
																				jButton2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				38,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel6Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jButton8,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								38,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								38,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel6Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jButton9,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								38,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								38,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel6Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jButton10,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								38,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton5,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								38,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel6Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jButton6,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								38,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton11,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								38,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jButton7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				38,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel6Layout
																		.createSequentialGroup()
																		.addGap(
																				30,
																				30,
																				30)
																		.addGroup(
																				jPanel6Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jButton13,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								141,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton12,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								141,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel6Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jButton14,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								139,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton15,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								140,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap(45, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel4Layout.createSequentialGroup().addGap(94, 94, 94)
						.addComponent(jLabel1).addContainerGap(169,
								Short.MAX_VALUE)).addComponent(jPanel5,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jTextField1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 411,
						Short.MAX_VALUE).addComponent(jPanel6,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel5,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jTextField1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												33,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel6,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel3Layout.createSequentialGroup().addContainerGap(432,
						Short.MAX_VALUE).addComponent(jPanel4,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGap(358,
						358, 358)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel3Layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel4,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(43, Short.MAX_VALUE)));

		jPanel2.setBackground(new java.awt.Color(77, 75, 77));

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/picture/箭头.png"))); // NOI18N
		jButton1.setBorder(null);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24));
		jLabel13.setForeground(new java.awt.Color(255, 255, 255));
		jLabel13.setText("\u5269\u4f59\u65f6\u95f4");

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setText("5:00");

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel3.setText("jLabel3");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jButton1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												98,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(442, 442, 442)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				10,
																				10,
																				10)
																		.addComponent(
																				jLabel6,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
														.addComponent(jLabel13))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel3).addContainerGap(
												461, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				26,
																				26,
																				26)
																		.addComponent(
																				jButton1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				47,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel13,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				37,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel3,
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								27,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel6,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))))
										.addContainerGap(44, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanel2,
						javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel3,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:

		try {
			if (Contrast(jTextField1.getText()) == true) {
				System.out.println("回答正确");
				JOptionPane.showMessageDialog(new JPanel(), "你赢了");
			} else
				System.out.println("回答错误");
			JOptionPane.showMessageDialog(new JPanel(), "答案错误");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			System.out.println("回答错误");
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		p = 1;
		// TODO add your handling code here:
		String text = jTextField1.getText();
		int i = text.length();
		if (i == 1) {
			String text3 = text.substring(i - 1);
			text = text.substring(0, i - 1);
			if (text3.indexOf(Integer.toString(t[0])) != -1) {
				jButton12.setEnabled(true);
			}
			if (text3.indexOf(Integer.toString(t[1])) != -1) {
				jButton13.setEnabled(true);
			}
			if (text3.indexOf(Integer.toString(t[2])) != -1) {
				jButton14.setEnabled(true);
			}
			if (text3.indexOf(Integer.toString(t[3])) != -1) {
				jButton15.setEnabled(true);
			}
			;
			jTextField1.setText(null);

		}
		if (i == 2) {
			text = text.substring(0, i - 1);
			jTextField1.setText(text);
		}
		System.out.println();
		if (jTextField1.getText().equals("")) {
			jButton12.setEnabled(true);
			jButton13.setEnabled(true);
			jButton14.setEnabled(true);
			jButton15.setEnabled(true);

		}
		if (i > 2) {
			String text2 = text.substring(i - 2);

			if (text2.indexOf(Integer.toString(t[0])) != -1) {
				jButton12.setEnabled(true);
			}
			if (text2.indexOf(Integer.toString(t[1])) != -1) {
				jButton13.setEnabled(true);
			}
			if (text2.indexOf(Integer.toString(t[2])) != -1) {
				jButton14.setEnabled(true);
			}
			if (text2.indexOf(Integer.toString(t[3])) != -1) {
				jButton15.setEnabled(true);
			}
			if ((text2.indexOf('+') != -1) || (text2.indexOf('-') != -1)
					|| (text2.indexOf('*') != -1) || (text2.indexOf('/') != -1)
					|| (text2.indexOf('(') != -1) || (text2.indexOf(')') != -1)) {
				text = text.substring(0, i - 1);
			} else if (Integer.parseInt(text2) > 10)
				text = text.substring(0, i - 2);

			// 退格，将文本最后一个字符去掉

			if (text.length() == 0) {
				// 如果文本没有了内容，则初始化计算器的各种值
				jTextField1.setText(null);
			} else {
				jTextField1.setText(text);

			}
		}
	}

	private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {
		if (p == 1) {
			jTextField1.setText(jTextField1.getText() + t[3]);
			jButton15.setEnabled(false);
			p = 0;
		}
	}

	private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {
		if (p == 1) {
			jTextField1.setText(jTextField1.getText() + t[2]);
			jButton14.setEnabled(false);
			p = 0;
		}
	}

	private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {
		if (p == 1) {
			jTextField1.setText(jTextField1.getText() + t[1]);
			jButton13.setEnabled(false);
			p = 0;
		}
	}

	private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
		if (p == 1) {
			jTextField1.setText(jTextField1.getText() + t[0]);
			jButton12.setEnabled(false);
			p = 0;
		}
	}

	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
		p = 1;
		Random r = new Random();
		int a = r.nextInt(53);
		int b = r.nextInt(53);
		int c = r.nextInt(53);
		int d = r.nextInt(53);
		t[0] = suiji(a, jButton12);
		t[1] = suiji(b, jButton13);
		t[2] = suiji(c, jButton14);
		t[3] = suiji(d, jButton15);
		System.out.println(t[0]);
		System.out.println(t[1]);
		System.out.println(t[2]);
		System.out.println(t[3]);
		jButton12.setEnabled(true);
		jButton13.setEnabled(true);
		jButton14.setEnabled(true);
		jButton15.setEnabled(true);
		jTextField1.setText(null);
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		jTextField1.setText(jTextField1.getText() + ")");
		p = 1;
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		jTextField1.setText(jTextField1.getText() + "(");
		p = 1;
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		jTextField1.setText(jTextField1.getText() + "/");
		p = 1;
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		jTextField1.setText(jTextField1.getText() + "*");
		p = 1;
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		jTextField1.setText(jTextField1.getText() + "-");
		p = 1;
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		jTextField1.setText(jTextField1.getText() + "+");
		p = 1;
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new zhu().setVisible(true);
		this.dispose();
	}

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jTextField1.setText(null);
		jButton12.setEnabled(true);
		jButton13.setEnabled(true);
		jButton14.setEnabled(true);
		jButton15.setEnabled(true);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new dj24dian().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton15;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}