/*
 * djca.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.Random;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import model.DataConnect;
import model.User;
import model.difference;
import model.tread;

/**
 * 
 * @author __USER__
 */
public class djca extends javax.swing.JFrame {

	/**
	 * Creates new form djca
	 * 
	 * @param u
	 */
	public djca() {

		initComponents();
		this.setLocationRelativeTo(null);
		final int time = 60;
		final tread t = new tread(time, jLabel3, jLabel9);
		t.start();
		jPanel1.addMouseListener(new MouseAdapter() {
			difference c = new difference(4);
			int[] a = random();
			boolean j1 = true;
			boolean j2 = true;
			boolean j3 = true;
			int num = 3;
			difference d1 = new difference(j1, j2, j3, num);
			difference d2 = new difference(j1, j2, j3, num);
			difference d3 = new difference(j1, j2, j3, num);
			difference d4 = new difference(j1, j2, j3, num);
			difference d = null;

			@SuppressWarnings("deprecation")
			public void mouseClicked(MouseEvent e) {
				if (e.getButton() == e.BUTTON1) {
					int x = e.getX();
					int y = e.getY();
					String banner = "当前位置的坐标是" + x + ", " + y;
					jLabel6.setText(banner);
					try {
						jLabel4.setIcon(new javax.swing.ImageIcon(getClass()
								.getResource(tupianl(a[0])))); // NOI18N

						jLabel5.setIcon(new javax.swing.ImageIcon(getClass()
								.getResource(tupianr(a[0]))));
						d1.judge(x, y, a[0], jLabel1, d1, d);

						if (d1.getNum() == 0) {
							jLabel4.setIcon(new javax.swing.ImageIcon(
									getClass().getResource(tupianl(a[1])))); // NOI18N

							jLabel5.setIcon(new javax.swing.ImageIcon(
									getClass().getResource(tupianr(a[1]))));
							d2.judge(x, y, a[1], jLabel1, d2, d);
							if (d2.getNum() == 0) {
								jLabel4.setIcon(new javax.swing.ImageIcon(
										getClass().getResource(tupianl(a[2])))); // NOI18N

								jLabel5.setIcon(new javax.swing.ImageIcon(
										getClass().getResource(tupianr(a[2]))));
								d3.judge(x, y, a[2], jLabel1, d3, d);
							}
							if (d3.getNum() == 0) {
								jLabel4.setIcon(new javax.swing.ImageIcon(
										getClass().getResource(tupianl(a[3])))); // NOI18N

								jLabel5.setIcon(new javax.swing.ImageIcon(
										getClass().getResource(tupianr(a[3]))));
								d4.judge(x, y, a[3], jLabel1, d4, d);
							}
							if (d4.getNum() == 0) {
								t.stop();
								JOptionPane.showMessageDialog(new JPanel(),
										"恭喜你赢了");
								int a;
								a = 180 - t.fanghui();
								System.out.println("用时：" + a);
							}
						}
					} catch (SQLException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					} catch (ClassNotFoundException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}

				}
			}
		});

	}

	public void upScore(int i, int j) {
		try {
			String sql = "insert into find (uid,utime,uscore) values ('" + 123
					+ "','" + i + "','" + j + "')";
			DataConnect.getStat().executeUpdate(sql);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public int[] random() {
		int a[] = new int[4];
		int n = 4;// gaiwei10
		int b = 0;
		Random rand = new Random();
		boolean[] bool = new boolean[5];
		int num = 0;
		for (int i = 0; i < n; i++) {
			do {
				// 如果产生的数相同继续循环
				num = rand.nextInt(n) + 1;
			} while (bool[num]);
			bool[num] = true;
			a[b] = num;
			b++;
		}

		return a;

	}

	public String tupianl(int a) {
		String tupian = null;
		if (a == 1) {
			tupian = "/view/1.png";
		}
		if (a == 2) {
			tupian = "/view/3.png";
		}
		if (a == 3) {
			tupian = "/view/5.png";
		}
		if (a == 4) {
			tupian = "/view/7.png";
		}
		return tupian;

	}

	public String tupianr(int a) {
		String tupian = null;
		if (a == 1) {
			tupian = "/view/2.png";
		}
		if (a == 2) {
			tupian = "/view/4.png";
		}
		if (a == 3) {
			tupian = "/view/6.png";
		}
		if (a == 4) {
			tupian = "/view/8.png";
		}
		return tupian;

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jLabel13 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(53, 52, 54));

		jPanel2.setBackground(new java.awt.Color(77, 75, 77));

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/picture/箭头.png"))); // NOI18N
		jButton1.setBorder(null);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24));
		jLabel13.setForeground(new java.awt.Color(255, 255, 255));
		jLabel13.setText("\u5269\u4f59\u65f6\u95f4");

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1
				.setText("\u8fd8\u6ca1\u627e\u51fa\u4e0d\u540c\u7684\u4e2a\u6570\uff1a3");

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24));
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("5\uff1a00");

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("\u5750\u6807");

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel6.setText("jLabel6");

		jLabel9.setText("jLabel9");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout
										.createSequentialGroup()
										.addGap(124, 124, 124)
										.addComponent(
												jButton1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												98,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												92, Short.MAX_VALUE)
										.addComponent(
												jLabel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												231,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(139, 139, 139)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				10,
																				10,
																				10)
																		.addComponent(
																				jLabel3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				75,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addGap(
																												42,
																												42,
																												42)
																										.addComponent(
																												jLabel2)
																										.addGap(
																												15,
																												15,
																												15)
																										.addComponent(
																												jLabel6,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												526,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel9))))
														.addComponent(jLabel13))));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout
										.createSequentialGroup()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				32,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel2Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				jPanel2Layout
																						.createSequentialGroup()
																						.addContainerGap()
																						.addGroup(
																								jPanel2Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																										.addComponent(
																												jLabel13,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												37,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												jLabel2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												32,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												jLabel6,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												29,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addGroup(
																								jPanel2Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(
																												jLabel9,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												36,
																												Short.MAX_VALUE)
																										.addComponent(
																												jLabel3,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												36,
																												Short.MAX_VALUE)))
																		.addGroup(
																				jPanel2Layout
																						.createSequentialGroup()
																						.addGap(
																								25,
																								25,
																								25)
																						.addComponent(
																								jButton1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								47,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap()));

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/picture/1.png"))); // NOI18N

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/picture/2.png"))); // NOI18N

		jLabel7.setFont(new java.awt.Font("宋体", 0, 18));
		jLabel7.setText("\u70b9\u51fb\u5f00\u59cb\u6e38\u620f");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGap(54, 54, 54)
										.addComponent(
												jLabel4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												516,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												211, Short.MAX_VALUE)
										.addComponent(
												jLabel5,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												500,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(107, 107, 107)).addComponent(
								jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addGroup(
								jPanel1Layout.createSequentialGroup().addGap(
										581, 581, 581).addComponent(jLabel7)
										.addContainerGap(699, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(jPanel2,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18,
						18).addComponent(jLabel7).addGap(73, 73, 73).addGroup(
						jPanel1Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel5).addComponent(jLabel4))
						.addGap(140, 140, 140)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new zhu().setVisible(true);
		this.dispose();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new djca().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	// End of variables declaration//GEN-END:variables

}